management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

spring:
  application:
    name: hexagonal-poc
  datasource:
    url: jdbc:h2:mem:hexagonal-poc;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true

springdoc:
  show-actuator: true